# Generated by Django 6.0.4 on 2026-05-02 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamepicture',
            name='image',
        ),
        migrations.AddField(
            model_name='gamepicture',
            name='action_pic',
            field=models.ImageField(null=True, upload_to='actionimages'),
        ),
        migrations.AlterField(
            model_name='gamepicture',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pictures', to='raterapi.game'),
        ),
    ]
